In [1]:
import tensorflow as tf
import numpy as np

2023-12-13 19:22:29.902594: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
# get inputs from other script
from retriveve_conditions import prediction_inputs

Trying to merge 01646500
Trying to merge 01638500
Trying to merge 01618000
Trying to merge 01613000
Trying to merge 01608500


In [3]:
model_17hr = tf.keras.models.load_model('Models/model_17hrs.h5')
model_15hr = tf.keras.models.load_model('Models/model_15hrs.h5')
model_8hr = tf.keras.models.load_model('Models/model_8hrs.h5')
model_4hr = tf.keras.models.load_model('Models/model_4hrs.h5')

2023-12-13 19:22:52.664448: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
model_17hr.predict(prediction_inputs[0].astype(float).reshape(1,4))

1/1 [==============================] - 0s 134ms/step


array([[3.578153]], dtype=float32)

In [5]:
model_15hr.predict(prediction_inputs[1].astype(float).reshape(1,2))

1/1 [==============================] - 0s 53ms/step


array([[3.7987776]], dtype=float32)

In [6]:
model_8hr.predict(prediction_inputs[2].astype(float).reshape(1,3))

1/1 [==============================] - 0s 56ms/step


array([[3.8922486]], dtype=float32)

In [7]:
model_4hr.predict(prediction_inputs[3].astype(float).reshape(1,4))

1/1 [==============================] - 0s 61ms/step


array([[3.9170809]], dtype=float32)

In [10]:
tf.keras.models.load_model('Models/model_4hrs.h5').predict(prediction_inputs[3].astype(float).reshape(1,4))

1/1 [==============================] - 0s 63ms/step


array([[3.9170809]], dtype=float32)

In [8]:
prediction_inputs

(array(['2.15', '2.15', '2.15', '2.15'], dtype='<U4'),
 array(['2.15', '4.80'], dtype='<U4'),
 array(['2.15', '4.80', '3.88'], dtype='<U4'),
 array(['2.15', '4.80', '3.88', '3.08'], dtype='<U4'))

In [1]:
import tensorflow as tf
import numpy as np

# get inputs from other script
from retriveve_conditions import prediction_inputs

# func to get predict output to string
def predict_to_string(predict):
    predict = str(predict[0][0])[:4]
    return predict

# load model and get prediction from inputs
def get_predictions():
    predict_17hr = predict_to_string(tf.keras.models.load_model('Models/model_17hrs.h5')\
                                     .predict(prediction_inputs[0].astype(float).reshape(1,4)))
    predict_15hr = predict_to_string(tf.keras.models.load_model('Models/model_15hrs.h5')\
                                     .predict(prediction_inputs[1].astype(float).reshape(1,2)))
    predict_8hr = predict_to_string(tf.keras.models.load_model('Models/model_8hrs.h5')\
                                    .predict(prediction_inputs[2].astype(float).reshape(1,3)))
    predict_4hr = predict_to_string(tf.keras.models.load_model('Models/model_4hrs.h5')\
                                    .predict(prediction_inputs[3].astype(float).reshape(1,4)))
    return predict_17hr, predict_15hr, predict_8hr, predict_4hr


2023-12-19 19:51:29.301153: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Trying to merge 01646500
Trying to merge 01638500
Trying to merge 01618000
Trying to merge 01613000
Trying to merge 01608500


In [2]:
test = get_predictions()
test

2023-12-19 19:51:53.606602: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


1/1 [==============================] - 0s 58ms/step


('3.75', '4.37', '4.72', '5.11')