In [1]:
import tensorflow as tf
import numpy as np

2023-11-14 20:04:41.710503: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
# get inputs from other script
from retriveve_conditions import prediction_inputs

Trying to merge 01646500
Trying to merge 01638500
Trying to merge 01618000
Trying to merge 01613000
Trying to merge 01608500


In [3]:
model_17hr = tf.keras.models.load_model('Models/model_17hrs.h5')
model_15hr = tf.keras.models.load_model('Models/model_15hrs.h5')
model_8hr = tf.keras.models.load_model('Models/model_8hrs.h5')
model_4hr = tf.keras.models.load_model('Models/model_4hrs.h5')

2023-11-14 20:05:05.109773: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
model_17hr.predict(prediction_inputs[0].astype(float).reshape(1,4))

1/1 [==============================] - 0s 86ms/step


array([[2.7857475]], dtype=float32)

In [7]:
model_15hr.predict(prediction_inputs[1].astype(float).reshape(1,2))

1/1 [==============================] - 0s 52ms/step


array([[2.808885]], dtype=float32)

In [9]:
model_8hr.predict(prediction_inputs[2].astype(float).reshape(1,3))

1/1 [==============================] - 0s 54ms/step


array([[2.7977257]], dtype=float32)

In [10]:
model_4hr.predict(prediction_inputs[3].astype(float).reshape(1,4))

1/1 [==============================] - 0s 59ms/step


array([[2.7558134]], dtype=float32)

In [6]:
prediction_inputs

(array(['1.13', '1.13', '1.13', '1.13'], dtype='<U4'),
 array(['1.13', '2.80'], dtype='<U4'),
 array(['1.13', '2.80', '1.79'], dtype='<U4'),
 array(['1.13', '2.80', '1.79', '0.91'], dtype='<U4'))